language: python
python:
  - "3.4"  
cache: pip
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev
install:
  - pip install -r requirements.txt
script:
  - python3 tests/test_textToImage.py
  - python3 tests/test_tokenMgr.py
  # - py.test --cov-report term-missing --cov app -v